LibraryManagementSys/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('librarypatrons/',include('librarypatrons.urls',namespace='librarypatrons')),
    path('librarian/',include('librarian.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

librarian/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
app_name = 'librarian'
urlpatterns = [
    path('managebooks/',views.managebooks,name='managebooks'),
    path('add_book_details/',views.add_book_details,name='add_book_details'),
    path('view_book_details/',views.view_book_details,name='view_book_details'),
    path('edit_book_details/<int:book_id>',views.edit_book_details,name='edit_book_details'),
    path('delete_book_details/<int:book_id>', views.delete_book_details, name='delete_book_details'),
    path('book_application_list/', views.book_application_list, name='book_application_list'),
    path('search/', views.search_results, name='search_results'),

]

librarian/models.py
from django.db import models

class BookDetails(models.Model):
    BookTitle = models.CharField(max_length=300)
    BookId = models.CharField(max_length=300)
    Book_Year = [
        ('1styear', '1st yr'),
        ('2ndyear', '2nd yr'),
    ]
    BookYear = models.CharField(max_length=20, choices=Book_Year)
    published_year = models.CharField(max_length=300)
    remarks = models.TextField()


    def __str__(self):
        return self.BookTitle

librarian/views.py
from django.shortcuts import render , get_object_or_404, redirect
from .models import *
#from ..librarypatrons.models import BookApplicants


# Create your views here.
#manage books , users and borrowing activities
def managebooks(request):
    return render(request,'librarian/managebooks.html')

def add_book_details(request):
    if request.method == 'POST':
        BookTitle = request.POST.get('BookTitle')
        BookId = request.POST.get('BookId')
        BookYear = request.POST.get('BookYear')
        published_year = request.POST.get('published_year')
        remarks = request.POST.get('remarks')


        book_details = BookDetails(
            BookTitle=BookTitle,
            BookId=BookId,
            BookYear=BookYear,
            published_year=published_year,
            remarks=remarks

        )

        book_details.save()
        return render(request,'librarian/datainserted.html')
    return render(request,'librarianhomepage.html')

def view_book_details(request):
    book_details_list = BookDetails.objects.all()
    return render(request,'librarian/view_book_details.html',{'book_details_list':book_details_list})

def edit_book_details(request,book_id):
    book_details = get_object_or_404(BookDetails, id=book_id)
    if request.method == 'POST':
        book_details.BookTitle = request.POST.get('BookTitle')
        book_details.BookId = request.POST.get('BookId')
        book_details.BookYear = request.POST.get('BookYear')
        book_details.published_year = request.POST.get('published_year')
        book_details.remarks = request.POST.get('remarks')
        book_details.save()
        return redirect('librarian:view_book_details')
    else:
        return render(request,'librarian/edit_book_details.html',{'book_details':book_details})


def delete_book_details(request,book_id):
    book_details = get_object_or_404(BookDetails,id=book_id)
    if request.method=='POST':
        book_details.delete()
        return redirect('librarian:view_book_details')
    else:
        return render(request,'librarian/delete_book_details.html',{'book_details':book_details})


from librarypatrons.models import BookApplicants
def book_application_list(request):
    book_applications=BookApplicants.objects.all()
    return render(request,'librarian/book_application_list.html', {'book_applications':book_applications})

from django.db.models import Q

def search_results(request):
    query = request.GET.get('query')
    results = []
    if query:
        results = BookDetails.objects.filter(
            Q(BookTitle__icontains=query) | Q(remarks__icontains=query)
        )
    return render(request, 'search_results.html', {'results': results, 'query': query})


from datetime import datetime, timedelta
from django.shortcuts import render

# def accept_book_application(request, book_application_id):
#     # Your existing code to fetch the book application
#     book_application = ...
#
#     # Calculate due date (current date + 14 days)
#     current_date = datetime.now().date()
#     due_date = current_date + timedelta(days=14)
#
#     # Pass due date along with other data to the template
#     return render(request, 'librarian/book_applicants_page.html', {'book_application': book_application, 'due_date': due_date})

templates/librarian/book_application_list.html
{% extends 'Navbar/librariannavbar.html' %}
{% load static %}

<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Applications</title>
</head>
<body>
{% block body %}

<div class="container1" style="display: flex; justify-content: left; align-items: left; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">
<br><br><br>
    <h1>Book Applicants List<br><br><br></h1>

    <table border="2">
        <thead>
         <tr>
             <th>Name</th>
             <th>Email</th>
             <th>ID Card</th>
<!--            <th>Action </th>-->
         </tr>
        </thead>
        <tbody>
            {% for book_application in book_applications %}
        <tr>
           <td>{{book_application.name}}</td>
            <td>{{book_application.email}}</td>

            <td>
                {% if book_application.id_document %}
                <a href="{{book_application.id_document.url}}" target="_blank">Download ID</a>
                {% else %}
                No ID uploaded
                {% endif %}
            </td>
<!--            <td>-->
<!--                <a href="#" class="btn btn-success">Accept</a>-->
<!--                <a href ="#" class="btn btn-danger">Reject</a>-->
<!--            </td>-->
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    <style>
        table,th,td {
        border:2px solid black;
        }
    </style>
    {%endblock %}

</body>
</html>

templates/librarian/datainserted.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Data Inserted</h1>
</body>
</html>

templates/librarian/delete_book_details.html
{% extends 'Navbar/librariannavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}

<div class="container mt-5">
    <div class="row justify-content-left">
        <div class = "col-md-4">
            <div class="card">
                <div class="card-body">
                    <p>Are you sure you want to delete "{{book_details.BookTitle}}"?</p>
                    <form method="post" action="{% url 'librarian:delete_book_details' book_details.id%}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}
</body>
</html>

templates/librarian/edit_book_details.html
{% extends 'Navbar/librariannavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'path/to/bootstrap/css/bootstrap.min.css' %}">
</head>
<body>
{% block body %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <form method="post" action="#">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="BookTitle">BookTitle:</label>
                            <input type="text" class="form-control" name="BookTitle" value="{{ book_details.BookTitle }}" required>
                        </div>

                        <div class="form-group">
                            <label for="BookId"> BookId:</label>
                            <input type="text" class="form-control" name="BookId" value="{{ book_details.BookId }}" required>
                        </div>

                        <div class="form-group">
                            <label for="BookYear">BookYear:</label>
                            <select class="form-control" name="BookYear" required>
                                <option value="1styear" {% if book_details.BookYear == '1st yr' %}selected{% endif %}>1st yr</option>
                                <option value="2ndyear" {% if book_details.BookYear == '2nd yr' %}selected{% endif %}>2nd yr</option>
                                <!-- Add more options if needed -->
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="published_year">published_year:</label>
                            <input type="text" class="form-control" name="remarks" value="{{ book_details.remarks }}" required>
                        </div>

                        <div class="form-group">
                            <label for="Remarks">remarks:</label>
                            <textarea class="form-control" name="published_year" required>{{ book_details.published_year }}</textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/librarian/managebooks.html
{% extends 'Navbar/librariannavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Manage Books</title>
</head>
<body>
{% block body %}
<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

<br><br>
<div class="bodycontainer" style="display: block; border: 1px solid #ccc; padding: 70px; border-radius: 5px; background-color: #F5CBA7; margin: 0 auto; width: fit-content;">

<div>
    <div class = "container mt-9" >
        <h3> Posting Books</h3>
        <form method="post" action="{% url 'librarian:add_book_details' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for = "BookTitle">Book Title</label>
                <input type = "text" class = "form-control" name="BookTitle" id = "BookTitle" placeholder="Enter the Book title">
            </div>
            <div class="form-group">
                <label for = "BookId">BookId</label>
                <input type = "text" class = "form-control" name="BookId" id = "BookId" placeholder="Enter the Book IDn">
            </div>
            <div class="form-group">
                <label for = "BookYear">BookYear</label>
                <select class = "form-control" name="BookYear" id = "BookYear" placeholder="Enter the Book Year">
                    <option value="1st Year">1st yr</option>
                    <option value="2nd Year">2nd yr</option>
                    <option value="3rd Year">3rd yr</option>
                    <option value="4th Year">4th yr</option>
                </select>
                <div class="form-group">
                <label for = "published_year">Published_year</label>
                <input type = "text" class = "form-control" name="published_year" id = "published_year" placeholder="Enter the published year">
                </div>
                    <div class = "form-group">
                    <label for = "remarks">Remarks</label>
                    <textarea class = "form-control" name = "remarks" id = "remarks" rows = "2" placeholder="Enter your remarks "></textarea>
                    </div>

                <button type="submit" class="btn btn-success">Post the Book</button>
            </div>
        </form>
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

templates/librarian/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #FAE5D3;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .profile-container {
            max-width: 800px;
            background-color: #F5CBA7;
            border-radius: 10px;
            padding: 20px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #333;
        }

        .profile-info {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
        }

        .profile-info img {
            width: 100px;
            height: 100px;
            border-radius: 50%;
            margin-right: 20px;
        }

        .profile-info h2 {
            margin: 0;
            color: #333;
        }

        .profile-info p {
            margin: 5px 0;
            color: #666;
        }

        .button {
            display: inline-block;
            padding: 10px 20px;
            background-color: #5D6D7E;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
        }

        .button:hover {
            background-color: #0056b3;
        }

        .edit-form {
            display: none;
        }

        .edit-form input[type="text"],
        .edit-form input[type="email"] {
            width: calc(100% - 20px);
            padding: 10px;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <div class="container">
    <div class="profile-container">
        <h1>User Profile</h1>
        <div class="profile-info">

            <div>
                <h2>{{ user.first_name }} {{ user.last_name }}</h2>
                <p>Email: {{ user.email }}</p>
                <p>Role: Librarian</p>
            </div>
        </div>
        <a href="#" class="button" id="edit-profile-btn">Edit Profile</a>

        <form class="edit-form" id="edit-form" method="POST" action="{% url 'update_profile' %}">
            {% csrf_token %}
            <label for="first-name">First Name:</label>
            <input type="text" id="first-name" name="first_name" value="{{ user.first_name }}"><br>

            <label for="last-name">Last Name:</label>
            <input type="text" id="last-name" name="last_name" value="{{ user.last_name }}"><br>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" value="{{ user.email }}"><br>

            <input type="submit" class="button" value="Save">
        </form>
    </div>
</div>


    <script>
        document.getElementById('edit-profile-btn').addEventListener('click', function() {
            document.querySelector('.profile-info').style.display = 'none';
            document.querySelector('.edit-form').style.display = 'block';
        });
    </script>

</body>

</html>

templates/librarian/search_results.html
<!--&lt;!&ndash; search_results.html &ndash;&gt;-->
<!--{% load static %}-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <title>Search Results</title>-->
<!--</head>-->
<!--<body>-->
<!--    <h1>Search Results</h1>-->

<!--    <form method="GET" action="{% url 'search_results' %}">-->
<!--        <input type="text" name="query" placeholder="Search...">-->
<!--        <button type="submit">Search</button>-->
<!--    </form>-->

<!--    {% if query %}-->
<!--        <h2>Search Results for "{{ query }}"</h2>-->
<!--        {% if results %}-->
<!--            <ul>-->
<!--            {% for item in results %}-->
<!--                <li>{{ item }}</li>-->
<!--            {% endfor %}-->
<!--            </ul>-->
<!--        {% else %}-->
<!--            <p>No results found.</p>-->
<!--        {% endif %}-->
<!--    {% endif %}-->
<!--{% endblock %}-->
<!--</body>-->
<!--</html>-->

templates/librarian/view_book_details.html
{% extends 'Navbar/librariannavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

<div class="container mt-5">
<br><br><br><br><br><br><br><br><br><br><br><Br>
    <div class="row">
        {% for book_details in book_details_list %}

        <div class="col-md-4 mb-4">
                <div class="bodycontainer" style="display: block; border: 1px solid #ccc; padding: 20px; border-radius: 5px; background-color: #F5CBA7; margin: 0 auto; ">

            <div class="card">
                    <div class="card-body">
                    <h5 class="card-title">{{ book_details.BookTitle}}</h5>
                    <p class="card-text">BookId {{ book_details.BookId }}</p>
                    <p class="card-text">BookYear {{ book_details.BookYear }}</p>
                    <p class="card-text">published_year {{ book_details.published_year }}</p>
                    <p class="card-text">Remarks {{ book_details.remarks }}</p>

                    <a href="{% url 'librarian:edit_book_details' book_details.id %}" class="btn btn-primary">Edit</a>
                    <a href="{% url 'librarian:delete_book_details' book_details.id %}" class="btn btn-danger">Delete</a>

                </div>
            </div>
        </div>
            </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}
</body>
</html>