LibraryManagementSys/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('librarypatrons/',include('librarypatrons.urls',namespace='librarypatrons')),
    path('librarian/',include('librarian.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

librarian/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
app_name = 'librarian'
urlpatterns = [
    path('managebooks/',views.managebooks,name='managebooks'),
    path('add_book_details/',views.add_book_details,name='add_book_details'),
    path('view_book_details/',views.view_book_details,name='view_book_details'),
    path('edit_book_details/<int:book_id>',views.edit_book_details,name='edit_book_details'),
    path('delete_book_details/<int:book_id>', views.delete_book_details, name='delete_book_details'),
    path('book_application_list/', views.book_application_list, name='book_application_list'),
    path('search/', views.search_results, name='search_results'),

]

librarypatrons/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from .views import get_the_book

app_name='librarypatrons'


urlpatterns = [
    path('searchbooks/',views.searchbooks,name='librarypatrons/searchbooks'),
    path('book_details_list/',views.book_details_list,name='book_details_list'),
    path('submit_form/',views.submit_form,name='submit_form'),
    path('addlibpatronsprofile/',views.addlibpatronsprofile,name='addlibpatronsprofile'),
    path('get_the_book/<int:book_id>/',views.get_the_book,name='get_the_book'),
    path('contactmail',views.contactmail,name='contactmail'),
    path('feedback', views.feedback, name='feedback'),
    path('feedback1', views.feedback1, name='feedback1'),
]

templates/Navbar/librariannavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #E5A776">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SDP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'librarianhomepage' %}">Home</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarian:managebooks' %}">Manage Books</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarian:view_book_details' %}">View Books</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarian:book_application_list' %}">View Book Applicants</a>
        </li>



<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Dropdown-->
<!--          </a>-->
<!--          <ul class="dropdown-menu">-->
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
<!--            <li><a class="dropdown-item" href="#">Something else here</a></li>-->
<!--          </ul>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
<!--      <form class="d-flex" role="search" action="{% url 'librarian:search_results' %}" method="GET">-->
<!--    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">-->
<!--    <button class="btn btn-success" type="submit">Search</button>-->
<!--</form>-->


     <!-- <ul class = "navbar-nav ms-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'librarianhomepage' %}">Librarian</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarypatronshomepage' %}">Library Patrons</a>
        </li>
        </ul>-->

      <ul class = "navbar-nav ms-auto">
          <li>
            {% if user.is_authenticated %}
            <li class="nav-item">
          <span class="nav-link">Welcome,{{user.username}} </span>
          </li>
        <li class="nav-item">
          <a class="btn btn-primary mb1 black bg-darken-3" href="{% url 'profilepage' %}">Profile</a>
        </li>
          <li class="nav-item">
          <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
        </li>
          {% else%}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-success" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<!--<footer id = "sticky-footer" class="flex-shrink-0 py-2">-->
<!--  <div class = "container text-center">-->
<!--    <small> Copyright Ms.Anusha.M KL-University. All rights reserved</small>-->
<!--  </div>-->
<!--</footer>-->
<!--<style>-->
<!--  #sticky-footer {-->
<!--  position: fixed;-->
<!--  bottom: 0;-->
<!--  left: 0;-->
<!--  right: 0;-->
<!--  background-color: #454545;-->
<!--  color: white;-->
<!--  padding: 10px;-->
<!--  font-weight: bold;-->
<!--</style>-->
</body>
</html>

templates/Navbar/librarypatronsnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #E5A776">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'projecthomepage' %}">SDP</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'librarypatronshomepage' %}">Home</a>
        </li>

<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'librarypatrons:addlibpatronsprofile' %}">Profile</a>-->
<!--        </li>-->
        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarypatrons:book_details_list' %}">Search Books</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarypatrons:feedback' %}">FeedBack</a>
        </li>



        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
<!--            <li><a class="dropdown-item" href="{% url 'librarypatrons:feedback' %}">FeedBack</a></li>-->
<!--            <li><hr class="dropdown-divider"></li>-->
            <li><a class="dropdown-item" href="{% url 'librarypatrons:feedback1' %}">Thank you</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
<!--      <form class="d-flex" role="search">-->
<!--        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">-->
<!--        <button class="btn btn-success" type="submit">Search</button>-->
<!--      </form>-->
<!--      <ul class = "navbar-nav ms-auto">-->
<!--      <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'librarianhomepage' %}">Librarian</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="{% url 'librarypatronshomepage' %}">Library Patrons</a>-->
<!--        </li>-->
<!--        </ul>-->
      <ul class = "navbar-nav ms-auto">
          <li>
            {% if user.is_authenticated %}
            <li class="nav-item">
          <span class="nav-link">Welcome , {{user.username}} </span>
          </li>
          <li class="nav-item">
          <a class="btn btn-danger" href="{% url 'logout' %}">Logout</a>
        </li>
          {% else%}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'signup' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<!--<footer id = "sticky-footer" class="flex-shrink-0 py-2">-->
<!--  <div class = "container text-center">-->
<!--    <small> Copyright Ms.Anusha.M KL-University. All rights reserved</small>-->
<!--  </div>-->
<!--</footer>-->
<!--<style>-->
<!--  #sticky-footer {-->
<!--  position: fixed;-->
<!--  bottom: 0;-->
<!--  left: 0;-->
<!--  right: 0;-->
<!--  background-color: #454545;-->
<!--  color: white;-->
<!--  padding: 10px;-->
<!--  font-weight: bold;-->
<!--</style>-->
</body>
</html>

templates/Navbar/projectnavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg" style="background-color: #8F694A">
  <div class="container-fluid">
<a class="navbar-brand" href="{% url 'projecthomepage' %}" style="color: white;"><b>Library Management System</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#" style="color: white;"><b>Home</b></a>
        </li>

      </ul>
      <form class="d-flex" role="search" style="color: white;">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success" type="submit" style="color: white;" >Search</button>
      </form>

      <!--<ul class = "navbar-nav ms-auto">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'librarianhomepage' %}">Librarian</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'librarypatronshomepage' %}">Library Patrons</a>
        </li>
        </ul>-->
      <ul class = "navbar-nav ms-auto">
          <li>
            {% if user.is_authenticated %}
            <li class="nav-item">
          <span class="nav-link">Welcome , {{user.username}} </span>
          </li>

          <li class="nav-item">
          <a class="btn btn-danger" href="{% url 'logout' %}"style="color: white;"><b>Logout</b></a>
        </li>
          {% else%}
          <li class="nav-item">
          <a class="btn btn-warning" href="{% url 'signup' %}"style="color: white;"><b>Register</b></a>

        </li>
        <li class="nav-item">
          <a class="btn btn-success" href="{% url 'login' %}"style="color: white;"><b>Login</b></a>
        </li>

        {% endif %}
        </ul>
    </div>
  </div>
</nav>
{% block body %}

{% endblock %}
<!--<footer id = "sticky-footer" class="flex-shrink-0 py-2">-->
<!--  <div class = "container text-center">-->
<!--    <small> Copyright Ms.Anusha.M KL-University. All rights reserved</small>-->
<!--  </div>-->
<!--</footer>-->
<!--<style>-->
<!--  #sticky-footer {-->
<!--  position: fixed;-->
<!--  bottom: 0;-->
<!--  left: 0;-->
<!--  right: 0;-->
<!--  background-color: #454545;-->
<!--  color: white;-->
<!--  padding: 10px;-->
<!--  font-weight: bold;-->
<!--</style>-->
</body>
</html>