LibraryManagementSys/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('adminmodule.urls')),
    path('librarypatrons/',include('librarypatrons.urls',namespace='librarypatrons')),
    path('librarian/',include('librarian.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

librarian/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
app_name = 'librarian'
urlpatterns = [
    path('managebooks/',views.managebooks,name='managebooks'),
    path('add_book_details/',views.add_book_details,name='add_book_details'),
    path('view_book_details/',views.view_book_details,name='view_book_details'),
    path('edit_book_details/<int:book_id>',views.edit_book_details,name='edit_book_details'),
    path('delete_book_details/<int:book_id>', views.delete_book_details, name='delete_book_details'),
    path('book_application_list/', views.book_application_list, name='book_application_list'),
    path('search/', views.search_results, name='search_results'),

]

librarypatrons/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views
from .views import get_the_book

app_name='librarypatrons'


urlpatterns = [
    path('searchbooks/',views.searchbooks,name='librarypatrons/searchbooks'),
    path('book_details_list/',views.book_details_list,name='book_details_list'),
    path('submit_form/',views.submit_form,name='submit_form'),
    path('addlibpatronsprofile/',views.addlibpatronsprofile,name='addlibpatronsprofile'),
    path('get_the_book/<int:book_id>/',views.get_the_book,name='get_the_book'),
    path('contactmail',views.contactmail,name='contactmail'),
    path('feedback', views.feedback, name='feedback'),
    path('feedback1', views.feedback1, name='feedback1'),
]

templates/librarianpatrols/accepted_books.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Accepted Books</title>
</head>
<body>
{% block body %}
<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

<div class="container mt-5">
  <h2>Accepted Books</h2>
    <div class="row">
        {% for book_details in accepted_books %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="container1" style="display: flex; justify-content: center; align-items: center; height: 35vh; background-color: #F5CBA7; background-size: cover;">

                <div class="card-body">

                    <h5 class="card-title">{{ book_details.BookTitle}}</h5>
                  <p>
                    <strong>Book ID:</strong> {{ book_details.BookId }}
                    <br>
                    <strong>Book Year:</strong> {{ book_details.BookYear }}
                    <br>
                    <strong>Published Year:</strong> {{ book_details.published_year }}
                    <br>
                    <strong>Remarks:</strong> {{ book_details.remarks }}
                  </p>
                    <a href="{% url 'librarypatrons:get_the_book' book_details.id %}" class="btn btn-success">Get This Book</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

templates/librarianpatrols/addlibpatronsprofile.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>

</head>

<body>
{% block body %}

  <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
  <title>Book Application Form</title>
</head>
<body>

<div class="container mt-5">
  <h2>Book Application Form</h2>
  <form method="post" action="{% url 'librarypatrons:submit_form' %}">
    {% csrf_token %}

    <div class="profile">
      <p>First Name: {{ user.first_name }}</p>
      <p>Last Name: {{ user.last_name }}</p>
      <p>Phone Number: {{ user.phone_number }}</p>
      <p>Branch: {{ user.Branch }}</p>
      <p>Year: {{ user.year }}</p>
    </div>

    <div class-name="form-row">

      <div class="form-group col-md-6">
        <label for="first_name">First Name</label>
        <input type="text" class="form-control" name ='first_name' id="first_name" value="{{ user.first_name }}" placeholder="Enter your first name">
      </div>
      <div class="form-group col-md-6">
        <label for="last_name">Last Name</label>
        <input type="text" class="form-control" name ='last_name' id="last_name" value="{{ user.last_name }}" placeholder="Enter your last name">
      </div>
    </div>

    <div class="form-group">
      <label for="phone_number">Phone Number</label>
      <input type="tel" class="form-control" name ='phone_number' id="phone_number" value="{{ user.phone_number }}" placeholder="Enter your phone number">
    </div>

    <div class="form-group">
        <label for="Branch">Branch:</label>
        <select class="form-control" name="Branch" required>
          <option value="CSE" {% if user.Branch == 'CSE' %}selected{% endif %}>CSE</option>
          <option value="ECE" {% if user.Branch == 'ECE' %}selected{% endif %}>ECE</option>
          <option value="EEE" {% if user.Branch == 'EEE' %}selected{% endif %}>EEE</option>
          <option value="AgBSC" {% if user.Branch == 'AgBSC' %}selected{% endif %}>AgBSC</option>

        </select>
    </div>

    <div class="form-group">
        <label for="Year">Year:</label>
        <select class="form-control" name="Year" required>
          <option value="1styear" {% if user.Year == '1st yr' %}selected{% endif %}>1st yr</option>
          <option value="2ndyear" {% if user.Branch == '2nd yr' %}selected{% endif %}>2nd yr</option>
          <option value="3rdyear" {% if user.Year == '3rd yr' %}selected{% endif %}>3rd yr</option>
          <option value="4thyear" {% if user.Year == '4th yr' %}selected{% endif %}>4th yr</option>

        </select>
    </div>


    <button type="submit" class="btn btn-primary">Submit</button>
    <br><br><br><br><br>
  </form>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</body>
</html>

    </div>
</div>
{% endblock %}
</body>
</html>

templates/librarianpatrols/book_borrowed_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book Borrowed Confirmation</title>
</head>
<body>
    <h2>Book Borrowed Successfully</h2>
    <p>Thank you for borrowing the book "{{ book_details.title }}". Please remember to return it by {{ return_date }}.</p>
</body>
</html>

templates/librarianpatrols/feedback.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Feedback Form</title>
    <style>
        table {
            border: 8px outset;
            border-radius: 10px;
            border-spacing: 10px;
            padding: 20px;
            margin-left: auto;
            margin-right: auto;
        }

        th,
        td {
            padding: 5px;
        }
    </style>
</head>

<body>

    {% block body %}

<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

    <br><br><br>

<div class="bodycontainer" style="display: block; border: 1px solid #ccc; padding: 20px; border-radius: 5px; background-color: #F5CBA7; margin: 0 auto; width: fit-content;">

        <h2 style="text-align:center">Feedback Form</h2>
        <form method="POST" action="{% url 'librarypatrons:contactmail' %}">
            {% csrf_token %}
            <table style="width:50%" align="center">
                <tr>
                    <td>FirstName</td>
                    <td><input type="text" placeholder="Enter your firstname" name="firstname" /><br><br></td>
                </tr>
                <tr>
                    <td>LastName</td>
                    <td><input type="text" placeholder="Enter your lastname" name="lastname" /><br><br></td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="email" placeholder="Enter Email" name="email" /><br><br></td>
                </tr>
                <tr>
                    <td>BookId</td>
                    <td><input type="text" placeholder="Book Id" name="book_id" /><br><br></td>
                </tr>

                <tr>
                    <td colspan="2">
                        <label for="remarks">Remarks</label>
                        <textarea class="form-control" name="remarks" id="remarks" rows="2" placeholder="Enter your remarks"></textarea>
                    </td>
                </tr>
                <tr>
                    <td colspan="2" align="center"><input type="submit" class="btn btn-success"> </td>
                </tr>
            </table>
        </form>
        </div>
</div>
    {% endblock %}
</body>

</html>

templates/librarianpatrols/get_this_book.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Get the Book</title>
</head>
<body>
{% block body %}
<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

<div class="container mt-5">
    <h2>Get the Book</h2>

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                 <div class="container1" style="display: flex; justify-content: center; align-items: center; height: 40vh; background-color: #F5CBA7; background-size: cover;">
                <div class="card-body">
                    <h5 class="card-title">{{ book_details.BookTitle }}</h5>
                    <p class="card-text">
                        <strong>BookTitle :</strong> {{ book_details.BookTitle }}<br>
                        <strong>BookId :</strong> {{ book_details.get_book_type_display }}<br>
                        <strong>BookYear : </strong> {{ book_details.BookYear|linebreaks }}<br>
                        <strong>published_year :</strong> {{ book_details.published_year }}<br>
                        <strong>Remarks :</strong> {{ book_details.remarks|linebreaks }}
                    </p>
                </div>
                 </div>
            </div>
        </div>

        <div class="col-md-6">
            <form method="post" enctype="multipart/form-data" >
                {% csrf_token %}

                <!-- Hidden field to store the job_id -->
                <input type="hidden" name="book_id" value="{{ book_details.id }}">

                <div class="form-group">
                    <label for="name">Your Name:</label>
                    <input type="text" class="form-control" name="name" required>
                </div>

                <div class="form-group">
                    <label for="email">Your Email:</label>
                    <input type="email" class="form-control" name="email" required>
                </div>

                <div class="form-group">
                    <label for="id">ID card</label>
                    <input type="file" class="form-control-file" name="id_document" accept=".pdf, .doc, .docx" required>
                </div>

                <div class="form-group">
                    <label for="department">Department</label>
                    <textarea class="form-control" name="department" required></textarea>
                </div>

                <button type="submit" class="btn btn-success">Get this book</button>


            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

templates/librarianpatrols/payment_and_due_date.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Payment and Due Date</title>
</head>
<body>
{% block body %}
<div class="container">
    <h2>Payment and Due Date</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Book Details</h5>
                    <p class="card-text">
                        <strong>Book Title:</strong> {{ book_details.BookTitle }}
                        <br>
                        <strong>Book ID:</strong> {{ book_details.id }}
                        <br>
                        <strong>Book Year:</strong> {{ book_details.BookYear }}
                        <br>
                        <strong>Published Year:</strong> {{ book_details.published_year }}
                        <br>
                        <strong>Remarks:</strong> {{ book_details.remarks }}
                    </p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Payment Details</h5>
                    <form method="post">
                        {% csrf_token %}
                        <!-- Form fields for payment and due date -->
                        <div class="form-group">
                            <label for="payment_amount">Payment Amount:</label>
                            <input type="number" class="form-control" id="payment_amount" name="payment_amount" required>
                        </div>
                        <div class="form-group">
                            <label for="due_date">Due Date:</label>
                            <input type="date" class="form-control" id="due_date" name="due_date" required>
                        </div>
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

templates/librarianpatrols/searchbooks.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
<div class="container1" style="display: flex; justify-content: center; align-items: center; height: 100vh; background-image: url('{% static "images/bgimage.png" %}'); background-size: cover;">

<div class="container mt-5">
  <h2>Book Details List</h2>
    <div class="row">
        {% for book_details in book_details_list %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="container1" style="display: flex; justify-content: center; align-items: center; height: 35vh; background-color: #F5CBA7; background-size: cover;">

                <div class="card-body">

                    <h5 class="card-title">{{ book_details.BookTitle}}</h5>
                  <p>
                    <strong>BookId</strong>{{ book_details.BookId }}<br>
                    <strong>BookYear</strong>{{ book_details.BookYear }}<br>
                    <strong>published_year</strong>{{ book_details.published_year }}<br>
                    <strong>Remarks</strong>{{ book_details.remarks }}<br>

                  </p>
                    <a href="{% url 'librarypatrons:get_the_book' book_details.id %}" class="btn btn-success">Get This Book</a>
                </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

templates/librarianpatrols/thankyou.html
{% extends 'Navbar/librarypatronsnavbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thank You</title>
</head>
<body>
{% block body %}
            {% csrf_token %}

<h1>Thank you</h1>
 {% endblock %}
</body>
</html>